### ISSUE TITLE
Does not work with --twitch-low-latency

### ISSUE THREAD

**Issue by solomongrundy6** [2bc4/streamlink-ttvlol#11] opened 2022-12-13 02:59 UTC
I don't know if this is a normal part of how the proxy works, but when using the --twitch-low-latency option with streamlink, the ads are not blocked with the modified twitch.py.  It behaves the way vanilla streamlink works, pausing the stream while the ads run.  If it's a normal part of how the proxy works, it should be noted in the readme as it took me a while to figure it out and I'm sure others might have the same problem.

**Comment by Sokoloft** [comment] 2022-12-13 03:36
> I don't know if this is a normal part of how the proxy works, but when using the --twitch-low-latency option with streamlink, the ads are not blocked with the modified twitch.py. It behaves the way vanilla streamlink works, pausing the stream while the ads run. If it's a normal part of how the proxy works, it should be noted in the readme as it took me a while to figure it out and I'm sure others might have the same problem.

I don't have this issue at all, and I've had low latency enabled from the start. What flag have you used? The ttv.lol one? If so try the public luminous one ```https://eu.luminous.dev```.

**Comment by solomongrundy6** [comment] 2022-12-13 04:41
Yes, I use the ttv.lol one. I use streamlink through streamlink-twitch-gui. 

The full command line that gets passed to streamlink in my case is:
`streamlink --player=mpv --player-passthrough --hls-live-edge=3 --stream-segment-threads=1 --twitch-disable-ads --twitch-proxy-playlist=https://api.ttv.lol --retry-open=1 --retry-streams=1 https://twitch.tv/$CHANNEL/ best`

Maybe it's some combination of settings?  All I know is that when I remove --twitch-low-latency, the plugin works properly and not otherwise.

**Comment by Sokoloft** [comment] 2022-12-13 04:45
I'm using Twitch gui as well. I have the box checked for low latency streams. Unsure the full command that gets passed to streamlink but all I have in my custom parameters are my oauth key and the flag to use luminous-ttv. 

Try luminous. I've heard that sometimes ttv lol can get you a bad playlist and can still play ads. I'm unsure how true this is but I seen it somewhere. Someone had suggested to keep launching a stream and hope you get a proper playlist request where it'll block ads but that isn't ideal.

**Comment by Sokoloft** [comment] 2022-12-13 19:01
> I can't reproduce the issue, but you could try reloading the stream several times to rule out that it isn't just bad luck with returning a playlist with ads as @Sokoloft said.

Maybe they're noticing what I've been noticing since the latest release. Maybe 15 minutes in, it will pause once like its playing an ad and streamlink is skipping it. Once its done that, it doesn't do it again. I've mainly noticed it when using the ttv.lol proxy like I do with my laptop. I think I have noticed it once or twice on my desktop using luminous too.

**Comment by solomongrundy6** [comment] 2022-12-13 19:52
> I can't reproduce the issue, but you could try reloading the stream several times to rule out that it isn't just bad luck with returning a playlist with ads as @Sokoloft said.

Reloading doesn't help, this has been happening consistently for at least a few days since I had added the low latency option.

> Maybe they're noticing what I've been noticing since the latest release. Maybe 15 minutes in, it will pause once like its playing an ad and streamlink is skipping it. Once its done that, it doesn't do it again. I've mainly noticed it when using the ttv.lol proxy like I do with my laptop. I think I have noticed it once or twice on my desktop using luminous too.

No, this happens multiple times during a stream, even specifically when streamers say they're about to run ads.

Regardless of all that, switching to luminous seems to have alleviated the issue. Maybe it was a networking issue between me and that particular proxy server?  I'll leave it set this way for a couple days and see how it performs over time.  Feel free to close this issue for now, if you want - if I encounter it again on luminous I'll come back and comment again.

**Comment by 2bc4** [comment] 2022-12-14 16:47
>Maybe they're noticing what I've been noticing since the latest release. Maybe 15 minutes in, it will pause once like its playing an ad and streamlink is skipping it. Once its done that, it doesn't do it again.

Hmm I can't reproduce this either. Does it still happen if you revert to the first release? This commit could be causing issues https://github.com/2bc4/streamlink-ttvlol/commit/cd3851edf2a82a7d3e481cb77dc52f0c1e4c652e

**Comment by DannyDarth** [comment] 2022-12-14 18:49
luminous with streamlink twitch gui works amazingly. Just have to have the command prompt server open. I haven't received any ads since using it. TTVLOL proxy i do get ads and commercial breaks.

**Comment by Coldblackice** [comment] 2022-12-17 14:45
> _The full command line that gets passed to streamlink in my case is:_ `_streamlink --player=mpv --player-passthrough --hls-live-edge=3 --stream-segment-threads=1 --twitch-disable-ads --twitch-proxy-playlist=https://api.ttv.lol --retry-open=1 --retry-streams=1 https://twitch.tv/$CHANNEL/ best_`

Is that what's _actually_ getting passed, or only what streamlink-twitch-gui is _supposed_ to pass? 

If unsure, open any of `task-manager | "wmic process get name,commandline" | ProcessMonitor | ProcessHacker`, etc., enable the "commmand-line" column, and see which switches are being passed down the chain and if/where it's being stripped, e.g. is it streamlink-gui not properly passing the switch, is streamlink.exe stripping it out, python, etc.

Also try changing the ordering of switches around and see if that gets passed along in the same order, add a garbage switch to see if it's passed, etc.

> _luminous with streamlink twitch gui works amazingly. Just have to have the command prompt server open. I haven't received any ads since using it. TTVLOL proxy i do get ads and commercial breaks_.

Do you get much delay/latency?

**Comment by 2bc4** [comment] 2022-12-17 15:52
I'll close this as suggested. Feel free to open it if you encounter this issue again.

**Closed by 2bc4** 2022-12-17 15:52 UTC
